# Generated by Django 4.2.7 on 2023-12-20 14:14

import app_download.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_download', '0002_music_photo_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('path', models.FileField(upload_to=app_download.models.update_othername)),
            ],
        ),
    ]
